default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: auction-app_development
  host: localhost

test:
  <<: *default
  database: auction-app_test
  host: localhost


production:
  url: <%= ENV['DATABASE_URL'] %>
